/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TypescriptImport } from './routes/typescript'
import { Route as ReactImport } from './routes/react'
import { Route as JavascriptImport } from './routes/javascript'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TypescriptRoute = TypescriptImport.update({
  id: '/typescript',
  path: '/typescript',
  getParentRoute: () => rootRoute,
} as any)

const ReactRoute = ReactImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => rootRoute,
} as any)

const JavascriptRoute = JavascriptImport.update({
  id: '/javascript',
  path: '/javascript',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/javascript': {
      id: '/javascript'
      path: '/javascript'
      fullPath: '/javascript'
      preLoaderRoute: typeof JavascriptImport
      parentRoute: typeof rootRoute
    }
    '/react': {
      id: '/react'
      path: '/react'
      fullPath: '/react'
      preLoaderRoute: typeof ReactImport
      parentRoute: typeof rootRoute
    }
    '/typescript': {
      id: '/typescript'
      path: '/typescript'
      fullPath: '/typescript'
      preLoaderRoute: typeof TypescriptImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/javascript': typeof JavascriptRoute
  '/react': typeof ReactRoute
  '/typescript': typeof TypescriptRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/javascript': typeof JavascriptRoute
  '/react': typeof ReactRoute
  '/typescript': typeof TypescriptRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/javascript': typeof JavascriptRoute
  '/react': typeof ReactRoute
  '/typescript': typeof TypescriptRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/javascript' | '/react' | '/typescript'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/javascript' | '/react' | '/typescript'
  id: '__root__' | '/' | '/about' | '/javascript' | '/react' | '/typescript'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JavascriptRoute: typeof JavascriptRoute
  ReactRoute: typeof ReactRoute
  TypescriptRoute: typeof TypescriptRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JavascriptRoute: JavascriptRoute,
  ReactRoute: ReactRoute,
  TypescriptRoute: TypescriptRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/javascript",
        "/react",
        "/typescript"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/javascript": {
      "filePath": "javascript.tsx"
    },
    "/react": {
      "filePath": "react.tsx"
    },
    "/typescript": {
      "filePath": "typescript.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
